nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization','accept','content-type','Origin']
        expose_headers: []
        # expose_headers: ['Link']
        max_age: 0
    paths:
        '^/api/':
            origin_regex: false
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth', 'Content-type','Authorization','accept','content-type','Origin']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE','OPTIONS']
            max_age: 3600
        '^/':
            origin_regex: false
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
            hosts: ['^api.']
   