framework:
    workflows:
        off_request_validation:
            type : 'state_machine'
            marking_store :
                type: 'method'
                property: 'status'
            supports: 
                - App\Entity\OffRequest
            initial_marking: pending
            places:
                - pending
                - accepted
                - rejected
                - cancelled
            transitions:
                cancelled:
                    from: pending
                    to: cancelled
                accepted:
                    guard: is_granted('ROLE_MANAGER')
                    from: pending
                    to: accepted
                rejected:
                    guard: is_granted('ROLE_MANAGER')
                    from: pending
                    to: rejected
                cancel:
                    guard: is_granted('ROLE_ADMIN')
                    from: accepted
                    to: rejected
